/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.robatipoor;

import org.junit.Test;

public class JalaliCalendarTest {
    @Test
    public void testSomeLibraryMethod() {
    }
}
